language: elixir
sudo: false
elixir:
  - 1.5.1
  - 1.8.0
otp_release:
  - 18.3
  - 19.0
  - 20.0
matrix:
    exclude:
      - elixir: 1.51
        otp_release: 18.3
      - elixir: 1.5.1
        otp_release: 19.0
before_script:
  - mix local.hex --force
  - mix deps.get --only test
script: mix test
after_script:
  - MIX_ENV=docs mix deps.get
